version: '3'

services:
  postgres:
    image: postgres:15-alpine
    hostname: local.pg
    container_name: local.pg
    networks:
      - appnetwork
    volumes:
      - .volumes:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5442:5432"

  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: solution
    hostname: local.solution
    container_name: local.solution
    networks:
      - appnetwork
    ports:
      - "8100:8000"
    env_file:
      - .env
    depends_on:
      - postgres
    volumes:
      - .storage:/storage
    command: "/bin/bash -c /src/entrypoint.sh"


networks:
  appnetwork:
    driver: bridge