"""initial

Revision ID: c2fdc3fa227d
Revises: 
Create Date: 2024-10-05 22:41:12.858948

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c2fdc3fa227d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task_model',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('status', sa.Enum('in_queue', 'run', 'completed', name='taskstatuses'), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('exec_time', sa.Float(), nullable=True),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('task_model')
    # ### end Alembic commands ###
